---
# https://circleci.com/docs/docker
version: 2
jobs:
  build:
    docker:
      - image: jumanjiman/cci:20170530T0443-git-02c4a0c

    working_directory: ~/workdir/

    steps:
      - setup_remote_docker

      - checkout

      - run:
          name: Build the image
          command: |
            ci/build.sh

      - run:
          name: Test the image
          command: |
            ci/test.sh

      - deploy:
          name: Deploy from master branch
          # yamllint disable rule:line-length
          command: |
            if [[ ${CIRCLE_BRANCH} = master ]] && [[ -z ${CIRCLE_PR_NUMBER} ]]; then
              ci/publish.sh
            fi
