#!/bin/sh
set -e

cat > ci/vars <<EOF
export VERSION=2.10.3
export BUILD_DATE=$(date +%Y%m%dT%H%M)
export VCS_REF=$(git rev-parse --short HEAD)
export TAG=\${VERSION}-\${BUILD_DATE}-git-\${VCS_REF}
EOF
. ci/vars

docker-compose build
