#!/bin/sh
set -e
. ci/vars

docker login -u $USER -p $PASS

docker tag jumanjiman/downer jumanjiman/downer:${TAG}
docker tag jumanjiman/downer jumanjiman/downer:latest

docker push jumanjiman/downer:${TAG}
docker push jumanjiman/downer:latest

docker logout
